name: 'Portami'
description: 'You have ever wondered if it was possible to update your Portainer stack withotu leaving gihtub, well now it is possible'
branding:
  icon: 'upload-cloud'
  color: 'white'
inputs:
  endpoint: 
    description: 'Portainer endpoint'
    required: true
  access_token: 
    description: 'User access token with the right privilegis'
    required: true
  stack_name: 
    description: 'Stack name'
    required: true  
  file_path: 
    description: 'Path to the file to be updated'
    required: false
  prune: 
    description: 'Prune the stack'
    required: false
  pull: 
    description: 'Pull the stack'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
